// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBV3FiQgX6-V6rlkGYjnJfC_7eDs2KkqQ',
    appId: '1:1041607134369:web:d51717a5b7607ff19034e0',
    messagingSenderId: '1041607134369',
    projectId: 'brainrush-6d742',
    authDomain: 'brainrush-6d742.firebaseapp.com',
    storageBucket: 'brainrush-6d742.firebasestorage.app',
    measurementId: 'G-XEJ24ZDVH9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDdW7oy4aRCmQo3eJbq_mfkwIatO2gAyA4',
    appId: '1:1041607134369:android:80fe98cac5345e9b9034e0',
    messagingSenderId: '1041607134369',
    projectId: 'brainrush-6d742',
    storageBucket: 'brainrush-6d742.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqDkIMHP4_Xzh17qQsAv2XoQbEQpVFVGM',
    appId: '1:1041607134369:ios:95d43046779403439034e0',
    messagingSenderId: '1041607134369',
    projectId: 'brainrush-6d742',
    storageBucket: 'brainrush-6d742.firebasestorage.app',
    iosBundleId: 'com.example.brainrush.brainRush',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqDkIMHP4_Xzh17qQsAv2XoQbEQpVFVGM',
    appId: '1:1041607134369:ios:95d43046779403439034e0',
    messagingSenderId: '1041607134369',
    projectId: 'brainrush-6d742',
    storageBucket: 'brainrush-6d742.firebasestorage.app',
    iosBundleId: 'com.example.brainrush.brainRush',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBBV3FiQgX6-V6rlkGYjnJfC_7eDs2KkqQ',
    appId: '1:1041607134369:web:b6c2ea1cb59fb6369034e0',
    messagingSenderId: '1041607134369',
    projectId: 'brainrush-6d742',
    authDomain: 'brainrush-6d742.firebaseapp.com',
    storageBucket: 'brainrush-6d742.firebasestorage.app',
    measurementId: 'G-PXJ940E8JE',
  );
}
